### ISSUE TITLE
Can't change frequency when editing log

### ISSUE THREAD

**Issue by km4ack** [mbridak/FieldDayLogger#32]
**Describe the bug**
The frequency doesn't update when editing the contact previously logged.

Is it possible to manually set the frequency before logging first contact? 

**To Reproduce**
1. Log a contact without rig control enabled.
2. Attempt to edit frequency in the logged contact
3. Click save
4. Doesn't save. Defaults back to original frequency.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21
 - Browser firefox 111

**Comment by mbridak** [comment]
Fixed and pushed change to pypi.

**Comment by km4ack** [comment]
Can confirm it works. Thanks! Is it possible to manually set the frequency before logging contacts?

**Comment by mbridak** [comment]
Hmmm... No, Not yet at least, ;-) I'll try and get it in before the big day.
My Not1MM logger does that. Makes it easy to QSY and meet someone somewhere for a mult.

**Comment by mbridak** [comment]
I've pushed that change for setting the freq if no CAT control is available.

In the callsign field you enter the frequency in kilohertz like 14032.5 then press the spacebar.

**Comment by km4ack** [comment]
Nice! Thanks for the heads up. Updated to the latest. Works great!
