### ISSUE TITLE
[2024 FD] FT8 contacts log as type DIW and are not handled correctly

### ISSUE THREAD

**Issue by mathuin** [mbridak/FieldDayLogger#45]
**Describe the bug**
The FT8 contacts logged via WSJT-X were recorded as type DIW.  They were not included as digital QSOs for the purpose of calculating score.

**To Reproduce**
1. Configure fdlogger and wsjtx as normal for Field Day.
2. Make an FT8 contact.
3. Note that fdlogger shows `Digital: 0` in the title bar, and that the log records something like the following: 

```
105 N3BEN          1B  SC 2024-06-23 17:30:32 2024-06-23 17:30:00 14074823M 20  DIW
```

**Expected behavior**
I expected `Digital: 1` and the QSO points calculated correctly as a result.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian 11

**Additional context**
I'm hoping that I can figure out how to edit the database and correct this so it will generate the appropriate logs.

**Comment by mbridak** [comment]
Thanks for the report. I'll take a look at it when i get back from vacation.

**Comment by mathuin** [comment]
Turns out the real issue is an additional date_time field which moves everything to the right.  The following sqlite command appears to have repaired the database:
```
update contacts set frequency=band,band=mode,mode=power,power=grid,grid=opname,opname='' where frequency like '%:%';
```

**Comment by wvolz** [comment]
I had the same issue, and believe this query also deals with the unique_id column and moving the "opname" column. Of course I suspect this is not that big of a deal for reporting so this is just in case it's helpful.

```
update contacts set frequency=band,band=mode,mode=power,power=grid,grid=opname,opname=unique_id,unique_id=lower(hex(randomblob(16))) where frequency like '%:%';
```
